import{a as f,S as p,i as l}from"./assets/vendor-Bz4lgVUE.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const y="50192556-e4befb0963aba9fc8ac0fc72c";function g(s){return f.get("https://pixabay.com/api/",{params:{key:y,q:`${s}`,image_type:"photo",orientation:"horizontal",safesearch:"true"}})}const c=document.querySelector(".gallery"),u=document.querySelector(".loader");let h=new p(".gallery a");function L(s){const t=s.map(({webformatURL:a,largeImageURL:o,tags:e,likes:r,views:n,comments:m,downloads:d})=>`<li class="gallery-item">
            <a href="${o}" class="gallery-link">
                <img src="${a}" alt="${e}" class="gallery-image" />
                <p class="gallery-likes">Likes <span>${r}</span></p>
                <p class="gallery-views">Views <span>${n}</span></p>
                <p class="gallery-comments">Comments <span>${m}</span></p>
                <p class="gallery-downloads">Downloads <span>${d}</span></p>
            </a>
        </li>`).join("");c.innerHTML=t,h.refresh()}function w(){c.innerHTML=""}function $(){u.classList.remove("hidden")}function i(){u.classList.add("hidden")}const b=document.querySelector(".form");b.addEventListener("submit",s=>{s.preventDefault(),w();const t=s.target.elements["search-text"].value.trim();if(s.target.elements["search-text"].value="",t==="")return l.error({title:"Error",message:"Sorry, your don't write anything. Please try again!",color:"yellow"});$(),g(t).then(a=>{const o=a.data.hits;if(o.length===0)return i(),l.error({title:"Error",message:`Sorry, there are no images matching your search query ${t}. Please try again!`});i(),L(o)}).catch(a=>{i(),l.error({title:"Error",message:`Something went wrong: ${a.message}`})})});
//# sourceMappingURL=index.js.map
